USE SaymeDB 
GO
CREATE TABLE dbo.TagPost
   (id_post bigint NOT NULL,  
    id_tag  bigint NOT NULL,
 CONSTRAINT PK_TagPost PRIMARY KEY CLUSTERED 
(
	id_post ASC,
	id_tag ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE dbo.TagPost  WITH CHECK ADD  CONSTRAINT FK_TagPost_Post FOREIGN KEY(id_post)
REFERENCES dbo.Post (id)
GO
ALTER TABLE dbo.TagPost CHECK CONSTRAINT FK_TagPost_Post
GO
ALTER TABLE dbo.TagPost  WITH CHECK ADD  CONSTRAINT FK_TagPost_Tag FOREIGN KEY(id_tag)
REFERENCES dbo.Tag (id)
GO
ALTER TABLE dbo.TagPost CHECK CONSTRAINT FK_TagPost_Tag
GO